env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - standard
  - plugin:prettier/recommended
parserOptions:
  sourceType: module
plugins:
  - simple-import-sort
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
  simple-import-sort/sort: error
  prettier/prettier: error
